name: NodeJs CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Build docker image
        run: |
          docker build . --file Dockerfile --tag test:latest
 